"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import environ
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env_path = os.path.join(BASE_DIR, '.env')

if os.path.exists(env_path):
    environ.Env.read_env(env_path)
else:
    print("Warning: Dotenv does not exist")

env = environ.Env(
    DEBUG=(bool, False),
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'my_admin.apps.MyAdminConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'payment_gateway',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'auth_core',
    # 'my_admin',
    'fixtures',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # my middlewares #
    'corsheaders.middleware.CorsMiddleware',
    'payment_gateway.middlewares.CheckPaymentMethodConfigMiddleware',
    'payment_gateway.middlewares.CheckPaymentGatewayDefaultMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

if os.environ.get('POSTGRES_HOST'):
    # Production database settings
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'ecommercedb6225'),  # Your RDS database name
            'USER': 'root',  # Your RDS username
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),  # Will come from K8s secret
            'HOST': 'micro-ecommerce-backend-database-dkc2khuw7vll.cnqiyioyo2lq.us-east-1.rds.amazonaws.com',  # Your RDS endpoint
            'PORT': '5432'
        }
    }
else:
    # Local development database settings
    DATABASES = {
        'default': env.db()
    }

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'auth_core.User'

AUTHENTICATION_BACKENDS = (
    'my_admin.backends.AdminBackend',
)

REST_FRAMEWORK = {
    
   'DEFAULT_AUTHENTICATION_CLASSES': 
        ['rest_framework_simplejwt.authentication.JWTAuthentication']
    ,

    'DEFAULT_PAGINATION_CLASS': 
        'rest_framework.pagination.PageNumberPagination',
        'PAGE_SIZE': 12
    ,
}

LOGIN_URL = 'rest_framework:login'
LOGOUT_URL = 'rest_framework:logout'


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL =  '/media/'

MEDIA_BASE_PATH = 'uploads'

CORS_ORIGIN_ALLOW_ALL = True

# AWS MQ Settings
AWS_MQ_BROKER_USERID = os.environ.get('AWS_MQ_BROKER_USERID', 'admin')
AWS_MQ_BROKER_PASSWORD = os.environ.get('AWS_MQ_BROKER_PASSWORD')
AWS_MQ_BROKER_HOST = 'b-04266b8b-b5b7-4270-810c-24057b12085d.mq.us-east-1.amazonaws.com'
AWS_MQ_BROKER_PORT = '5671'
AWS_MQ_BROKER_VHOST = '/'

# Replace the existing CELERY_BROKER_URL with this
CELERY_BROKER_URL = f'amqps://{AWS_MQ_BROKER_USERID}:{AWS_MQ_BROKER_PASSWORD}@{AWS_MQ_BROKER_HOST}:{AWS_MQ_BROKER_PORT}/{AWS_MQ_BROKER_VHOST}'

'''
Config JWT
'''

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': '!71mw7$cvbm$_9i$xo09w!1ul*_dd+_-nqwotrqwtqynjk1zxu',
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}
